apiVersion: v1
kind: Namespace
metadata:
  name: webhook

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forbidden-keys
  namespace: webhook
data:
  FORBIDDEN_KEYS: >-
    API_KEYS, PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: webhook
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: webhook
  type: ClusterIP

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-configmap
  annotations:
    cert-manager.io/inject-ca-from: webhook/webhook-certificate
webhooks:
  - name: webhook-service.webhook.svc
    rules:
      - apiGroups:   ['']
        apiVersions: [v1]
        operations:  [CREATE, UPDATE]
        resources:   [configmaps]
        scope:       Namespaced
    clientConfig:
      service: 
        namespace: webhook
        name: webhook-service
        path: /mutate
        port: 443
    admissionReviewVersions: [v1]
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-configmap
  annotations:
    cert-manager.io/inject-ca-from: webhook/webhook-certificate
webhooks:
  - name: webhook-service.webhook.svc
    rules:
      - apiGroups:   ['']
        apiVersions: [v1]
        operations:  [CREATE, UPDATE]
        resources:   [configmaps]
        scope:       Namespaced
    clientConfig:
      service:
      service: 
        namespace: webhook
        name: webhook-service
        path: /validate
        port: 443
    admissionReviewVersions: [v1]
    sideEffects: None

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-certificate
  namespace: webhook
spec:
  secretName: webhook-certificate
  dnsNames:
    - webhook-service.webhook.svc
  issuerRef:
    name: selfsigned

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: webhook
spec:
  selfSigned: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: webhook
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: ghcr.io/nivesh00/configmap-admission-webhook:debug
        ports:
        - containerPort: 443
        command: ["/app/admission-webhook"]
        envFrom:
        - configMapRef:
            name: forbidden-keys
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
        - name: ssl-certs
          secret:
            secretName: webhook-certificate